// <auto-generated />
namespace FreeExp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IniCenterTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IniCenterTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201906240018285_IniCenterTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
